name: Java CI with Maven - Test and package

on: pull_request

jobs:
  BuildJava:
    name: BuildJava
    runs-on: ubuntu-latest
    steps:
      - name: Checkout depot courant
        uses: actions/checkout@v4.3.0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'corretto'
          java-version: '21'

      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Build Maven
        env:
          SONAR_TOKEN : ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=$(echo ${{ github.repository }} | sed 's-/-_-')
