name: Génération de la documentation

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  generate-doc:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout depot courant
        uses: actions/checkout@v4.3.0

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: generation de la javadoc
        run: mvn -B javadoc:javadoc

      - name: Déployer la documentation sur GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/site/apidocs
